FROM sphericalcowgroup/comanage-registry:%%COMANAGE_REGISTRY_VERSION%%-mod-auth-openidc

RUN apt-get update && apt-get install -y \
      libpcre3-dev \
      && wget -O oauth.tar.gz https://github.com/cilogon/pecl-web_services-oauth/archive/null_byte.tar.gz \
      && mkdir -p oauth \
      && tar zxf oauth.tar.gz -C oauth --strip-components=1 \
      && rm oauth.tar.gz \
      && ( \
          cd oauth \
          && phpize \
          && ./configure \
          && make \
          && make install \
          ) \
      && rm -r oauth \
      && docker-php-ext-enable oauth

ARG CILOGON_LDAP_SCHEMA_PLUGIN_SRC_URL=https://github.com/cilogon/CilogonLdapSchema/archive/master.tar.gz

RUN mkdir -p "$COMANAGE_REGISTRY_DIR/app/Plugin/CilogonLdapSchema" \
      && wget -O CilogonLdapSchema.tar.gz $CILOGON_LDAP_SCHEMA_PLUGIN_SRC_URL \
      && tar -zxf CilogonLdapSchema.tar.gz -C "$COMANAGE_REGISTRY_DIR/app/Plugin/CilogonLdapSchema" --strip-components=1 \
      && rm -f CilogonLdapSchema.tar.gz

COPY mod-auth-openidc.conf /etc/apache2/conf-enabled/mod-auth-openidc.conf

COPY docker-comanage-entrypoint /usr/local/bin/

# Default values for first administrator bootstrapped
# into the platform, most likely overridden at build time
# using build arguments.
ARG COMANAGE_REGISTRY_ADMIN_GIVEN_NAME
ARG COMANAGE_REGISTRY_ADMIN_FAMILY_NAME
ARG COMANAGE_REGISTRY_ADMIN_USERNAME
ARG COMANAGE_REGISTRY_ENABLE_POOLING

ENV COMANAGE_REGISTRY_ADMIN_GIVEN_NAME ${COMANAGE_REGISTRY_ADMIN_GIVEN_NAME:-Registry}
ENV COMANAGE_REGISTRY_ADMIN_FAMILY_NAME ${COMANAGE_REGISTRY_ADMIN_FAMILY_NAME:-Admin}
ENV COMANAGE_REGISTRY_ADMIN_USERNAME ${COMANAGE_REGISTRY_ADMIN_USERNAME:-registry.admin}
ENV COMANAGE_REGISTRY_ENABLE_POOLING ${COMANAGE_REGISTRY_ENABLE_POOLING:-No}
