#!/bin/bash

source /usr/local/lib/comanage_utils.sh

# Copy secrets and other deployment specific details into place
sed -i -e s@%%OIDCClientID%%@`cat ${OIDC_CLIENT_ID_FILE}`@ /etc/apache2/conf-enabled/mod-auth-openidc.conf
sed -i -e s@%%OIDCClientSecret%%@`cat ${OIDC_CLIENT_SECRET_FILE}`@ /etc/apache2/conf-enabled/mod-auth-openidc.conf
sed -i -e s@%%OIDCProviderMetadataURL%%@`cat ${OIDC_PROVIDER_METADATA_URL_FILE}`@ /etc/apache2/conf-enabled/mod-auth-openidc.conf
sed -i -e s@%%OIDCCryptoPassphrase%%@`cat ${OIDC_CRYPTO_PASSPHRASE_FILE}`@ /etc/apache2/conf-enabled/mod-auth-openidc.conf

comanage_utils::exec_apache_http_server "$@"
