version: '3.7'

networks:
    cilogon_service:
        driver: overlay
        ipam:
            config:
                - subnet: 10.0.109.0/24
    webgateway:
        external: true

volumes:
    cilogon_service_volume:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_service/"

services:
    oa4mp_demo:
      image: cilogon/oa4mp_demo:1
      command: ["catalina.sh", "run" ]
      volumes:
        - type: volume
          source: cilogon_service_volume
          target: /var/local/cilogon_service
          read_only: false
          volume:
            nocopy: true
      #environment:
      networks:
        - webgateway
        - cilogon_service
      deploy:
          labels:
                - "traefik.frontend.rule=Host: demo-dev.cilogon.org"
                - "traefik.backend=cilogon_service-oa4mp_demo"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=cilogon_service_demo_dev_cilogon_org"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=8888"
          replicas: 1
      logging:
        driver: journald
        options:
          tag: "cilogon_docker_{{.Name}}"
