version: '3.8'

networks:
    cilogon_service:
        driver: overlay
        ipam:
            config:
                - subnet: 10.0.109.0/24
    webgateway:
        external: true

volumes:
    cilogon_service_volume_dedicated:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_CILOGON_SERVICE_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/"

services:
    cilogon-crl:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/cilogon-crl:15
        command: ["apache2-foreground"]
        volumes:
            - type: volume
              source: cilogon_service_volume_dedicated
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - cilogon_service
            - webgateway
        healthcheck:
            test: ["CMD", "curl", "-f", "-I", "-L", "http://127.0.0.1/"]
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 30s
        extra_hosts:
            myproxy.cilogon.org: 141.142.149.36
        deploy:
            mode: replicated
            replicas: 1
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 30s
                failure_action: rollback
                order: start-first
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=webgateway"
                - "traefik.http.routers.cilogon-crl.entrypoints=web"
                - "traefik.http.routers.cilogon-crl.rule=Host(`crl-dev.cilogon.org`,`crl-cilogon-dev.ncsa-security.net`,`crl-dev.cilogon.com`,`crl-dev.cilogon.net`,`crl-dev.cilogin.org`)"
                - "traefik.http.routers.cilogon-crl-https.entrypoints=websecure"
                - "traefik.http.routers.cilogon-crl-https.rule=Host(`crl-dev.cilogon.org`,`crl-cilogon-dev.ncsa-security.net`,`crl-dev.cilogon.com`,`crl-dev.cilogon.net`,`crl-dev.cilogin.org`)"
                - "traefik.http.routers.cilogon-crl-https.tls=true"
                - "traefik.http.routers.cilogon-crl.middlewares=cilogon-crl-ratelimit"
                - "traefik.http.services.cilogon-crl.loadbalancer.server.port=80"
                - "traefik.http.services.cilogon-crl.loadbalancer.sticky.cookie=true"
                - "traefik.http.services.cilogon-crl.loadbalancer.sticky.cookie.name=_crl_dev_cilogon_org"
                - "traefik.http.services.cilogon-crl.loadbalancer.sticky.cookie.httpOnly=true"
                - "traefik.http.services.cilogon-crl.loadbalancer.healthcheck.path=/"
                - "traefik.http.services.cilogon-crl.loadbalancer.healthcheck.interval=30s"
                - "traefik.http.services.cilogon-crl.loadbalancer.healthcheck.timeout=3s"
                - "traefik.http.middlewares.cilogon-crl-ratelimit.ratelimit.average=4"
                - "traefik.http.middlewares.cilogon-crl-ratelimit.ratelimit.burst=40"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    oa4mp-demo:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/oa4mp-demo:9
        command: ["catalina.sh", "run"]
        volumes:
            - type: volume
              source: cilogon_service_volume_dedicated
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - cilogon_service
            - webgateway
        healthcheck:
            test: ["CMD", "curl", "-f", "-I", "-L", "http://127.0.0.1:8888/cilogon2/"]
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 60s
        deploy:
            mode: replicated
            replicas: 1
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 60s
                failure_action: rollback
                order: start-first
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=webgateway"
                - "traefik.http.routers.oa4mp-demo-http.entrypoints=web"
                - "traefik.http.routers.oa4mp-demo-http.rule=Host(`demo-dev.cilogon.org`)"
                - "traefik.http.routers.oa4mp-demo-http.middlewares=oa4mp-demo-https"
                - "traefik.http.middlewares.oa4mp-demo-https.redirectscheme.scheme=https"
                - "traefik.http.routers.oa4mp-demo.entrypoints=websecure"
                - "traefik.http.routers.oa4mp-demo.rule=Host(`demo-dev.cilogon.org`)"
                - "traefik.http.routers.oa4mp-demo.tls=true"
                - "traefik.http.routers.oa4mp-demo.middlewares=oa4mp-demo,oa4mp-demo-ratelimit"
                - "traefik.http.services.oa4mp-demo.loadbalancer.server.port=8888"
                - "traefik.http.services.oa4mp-demo.loadbalancer.sticky.cookie=true"
                - "traefik.http.services.oa4mp-demo.loadbalancer.sticky.cookie.name=_demo_dev_cilogon_org"
                - "traefik.http.services.oa4mp-demo.loadbalancer.sticky.cookie.secure=true"
                - "traefik.http.services.oa4mp-demo.loadbalancer.sticky.cookie.httpOnly=true"
                - "traefik.http.services.oa4mp-demo.loadbalancer.healthcheck.path=/cilogon2/"
                - "traefik.http.services.oa4mp-demo.loadbalancer.healthcheck.interval=30s"
                - "traefik.http.services.oa4mp-demo.loadbalancer.healthcheck.timeout=3s"
                - "traefik.http.middlewares.oa4mp-demo.headers.stsseconds=63072000"
                - "traefik.http.middlewares.oa4mp-demo-ratelimit.ratelimit.average=4"
                - "traefik.http.middlewares.oa4mp-demo-ratelimit.ratelimit.burst=40"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    oa4mp-server:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/oa4mp-server:19
        command: ["catalina.sh", "run"]
        volumes:
            - type: volume
              source: cilogon_service_volume_dedicated
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - cilogon_service
            - webgateway
        healthcheck:
            test: ["CMD", "curl", "-f", "-I", "-L", "http://127.0.0.1:8888/oauth2/dbService?action=getUser&idp=http%3A%2F%2Fgoogle.com%2Faccounts%2Fo8%2Fid&idp_display_name=Google&first_name=Google&last_name=User&display_name=Google+User&email=google%40cilogon.org&loa=openid&oidc=112618836080811307185&us_idp=1"]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 60s
        extra_hosts:
            myproxy.cilogon.org: 141.142.149.24
            myproxy2.cilogon.org: 141.142.149.36
        deploy:
            mode: replicated
            replicas: 1
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 60s
                failure_action: rollback
                order: start-first
            resources:
                reservations:
                    memory: 512M
                limits:
                    memory: 3072M
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=webgateway"
                - "traefik.http.routers.oa4mp-server-http.entrypoints=web"
                - "traefik.http.routers.oa4mp-server-http.rule=Host(`dev.cilogon.org`) &&
                    PathPrefix(
                      `/oauth2/{url1:(token|userinfo|getcert|register|certs|clients|static|oidc-cm|admin-register|revoke|introspect|device_authorization|device|\\.well-known)}`,
                      `/{url2:([^/]+)/\\.well-known/(openid-configuration|oauth-authorization-server)}`,
                      `/{url3:\\.well-known/(openid-configuration|oauth-authorization-server)/([^/]+)}`
                    )"
                - "traefik.http.routers.oa4mp-server-http.middlewares=oa4mp-server-https"
                - "traefik.http.middlewares.oa4mp-server-https.redirectscheme.scheme=https"
                - "traefik.http.routers.oa4mp-server.entrypoints=websecure"
                - "traefik.http.routers.oa4mp-server.rule=Host(`dev.cilogon.org`) &&
                    PathPrefix(
                      `/oauth2/{url1:(token|userinfo|getcert|register|certs|clients|static|oidc-cm|admin-register|revoke|introspect|device_authorization|device|\\.well-known)}`,
                      `/{url2:([^/]+)/\\.well-known/(openid-configuration|oauth-authorization-server)}`,
                      `/{url3:\\.well-known/(openid-configuration|oauth-authorization-server)/([^/]+)}`
                    )"
                - "traefik.http.routers.oa4mp-server.tls=true"
                - "traefik.http.routers.oa4mp-server.middlewares=oa4mp-server,oa4mp-server-ratelimit,oa4mp-regex1,oa4mp-regex2"
                - "traefik.http.services.oa4mp-server.loadbalancer.server.port=8888"
                - "traefik.http.services.oa4mp-server.loadbalancer.sticky.cookie=true"
                - "traefik.http.services.oa4mp-server.loadbalancer.sticky.cookie.name=_dev_cilogon_org_oauth2"
                - "traefik.http.services.oa4mp-server.loadbalancer.sticky.cookie.secure=true"
                - "traefik.http.services.oa4mp-server.loadbalancer.sticky.cookie.httpOnly=true"
                - "traefik.http.services.oa4mp-server.loadbalancer.healthcheck.path=/oauth2/dbService?action=getUser&idp=http%3A%2F%2Fgoogle.com%2Faccounts%2Fo8%2Fid&idp_display_name=Google&first_name=Google&last_name=User&display_name=Google+User&email=google%40cilogon.org&loa=openid&oidc=112618836080811307185&us_idp=1"
                - "traefik.http.services.oa4mp-server.loadbalancer.healthcheck.interval=30s"
                - "traefik.http.services.oa4mp-server.loadbalancer.healthcheck.timeout=5s"
                # This horrible regex is equivalent to (?!oauth2) in Perl (due to lack of negative lookahead in Golang)
                - "traefik.http.middlewares.oa4mp-regex1.replacepathregex.regex=^/(([^o]|o(o|a(o|u(o|t(o|ho))))*([^ao]|a([^ou]|u([^ot]|t([^ho]|h[^2o])))))*(o(o|a(o|u(o|t(o|ho))))*(a(u?|uth?))?)?)/\\.well-known/(openid-configuration|oauth-authorization-server)/?"
                - "traefik.http.middlewares.oa4mp-regex1.replacepathregex.replacement=/oauth2/.well-known/$${18}/$${1}"
                - "traefik.http.middlewares.oa4mp-regex2.replacepathregex.regex=^/\\.well-known/(openid-configuration|oauth-authorization-server)/([^/]+)/?"
                - "traefik.http.middlewares.oa4mp-regex2.replacepathregex.replacement=/oauth2/.well-known/$${1}/$${2}"
                - "traefik.http.middlewares.oa4mp-server.headers.stsseconds=63072000"
                - "traefik.http.middlewares.oa4mp-server-ratelimit.ratelimit.average=4"
                - "traefik.http.middlewares.oa4mp-server-ratelimit.ratelimit.burst=40"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    cilogon-web:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/cilogon-web:51
        command: ["/usr/local/bin/startup.sh"]
        volumes:
            - type: volume
              source: cilogon_service_volume_dedicated
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - cilogon_service
            - webgateway
        healthcheck:
            test: ["CMD", "curl", "-f", "-I", "-L", "http://127.0.0.1/"]
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 30s
        extra_hosts:
            myproxy.cilogon.org: 141.142.149.24
            myproxy2.cilogon.org: 141.142.149.36
        deploy:
            mode: replicated
            replicas: 1
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 30s
                failure_action: rollback
                order: start-first
            resources:
                reservations:
                    memory: 512M
                limits:
                    memory: 4096M
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=webgateway"
                - "traefik.http.routers.cilogon-web-http.entrypoints=web"
                - "traefik.http.routers.cilogon-web-http.rule=Host(`dev.cilogon.org`,`dev.cilogon.com`,`dev.cilogon.net`,`dev.cilogin.org`)"
                - "traefik.http.routers.cilogon-web-http.middlewares=cilogon-web-https"
                - "traefik.http.middlewares.cilogon-web-https.redirectscheme.scheme=https"
                - "traefik.http.routers.cilogon-web.entrypoints=websecure"
                - "traefik.http.routers.cilogon-web.rule=Host(`dev.cilogon.org`,`dev.cilogon.com`,`dev.cilogon.net`,`dev.cilogin.org`)"
                - "traefik.http.routers.cilogon-web.tls=true"
                - "traefik.http.routers.cilogon-web.middlewares=cilogon-web,cilogon-web-ratelimit"
                - "traefik.http.services.cilogon-web.loadbalancer.server.port=80"
                - "traefik.http.services.cilogon-web.loadbalancer.sticky.cookie=true"
                - "traefik.http.services.cilogon-web.loadbalancer.sticky.cookie.name=_dev_cilogon_org"
                - "traefik.http.services.cilogon-web.loadbalancer.sticky.cookie.secure=true"
                - "traefik.http.services.cilogon-web.loadbalancer.sticky.cookie.httpOnly=true"
                - "traefik.http.services.cilogon-web.loadbalancer.healthcheck.path=/"
                - "traefik.http.services.cilogon-web.loadbalancer.healthcheck.interval=30s"
                - "traefik.http.services.cilogon-web.loadbalancer.healthcheck.timeout=3s"
                - "traefik.http.middlewares.cilogon-web.headers.stsseconds=63072000"
                - "traefik.http.middlewares.cilogon-web-ratelimit.ratelimit.average=4"
                - "traefik.http.middlewares.cilogon-web-ratelimit.ratelimit.burst=40"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    cilogon-cron:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/cilogon-cron:7
        command: ["/usr/sbin/cron", "-f", "-L", "15"]
        volumes:
            - type: volume
              source: cilogon_service_volume_dedicated
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - cilogon_service
            - webgateway
        healthcheck:
            test: ["CMD-SHELL", "ps aux | grep '[c]ron' || exit 1"]
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 30s
        extra_hosts:
            myproxy.cilogon.org: 141.142.149.36
            myproxy2.cilogon.org: 141.142.149.38
        deploy:
            mode: replicated
            replicas: 1
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 30s
                failure_action: rollback
                order: start-first
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=webgateway"
                - "traefik.http.services.cilogon-cron.loadbalancer.server.port=80"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

