version: '3.8'

networks:
    cilogon_service:
        driver: overlay
        ipam:
            config:
                - subnet: 10.0.109.0/24
    webgateway:
        external: true

volumes:
    cilogon_service_volume:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_service/"

services:
    cilogon-crl:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/cilogon-crl:2
        hostname: crl-dev.cilogon.org
        command: ["apache2-foreground"]
        volumes:
            - type: volume
              source: cilogon_service_volume
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - webgateway
            - cilogon_service
        extra_hosts:
            myproxy.cilogon.org: 141.142.149.29
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 60s
            labels:
                - "traefik.frontend.rule=Host:crl-dev.cilogon.org,crl-cilogon-dev.ncsa-security.net"
                - "traefik.backend=cilogon_service-cilogon-crl"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookiename=cilogon_service_crl_dev_cilogon_org"
                - "traefik.port=80"
                - "traefik.frontend.entrypoints=http"
                - "traefik.frontend.headers.sslredirect=false"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    oa4mp-demo:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/oa4mp-demo:1
        hostname: demo-dev.cilogon.org
        command: ["catalina.sh", "run"]
        volumes:
            - type: volume
              source: cilogon_service_volume
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - webgateway
            - cilogon_service
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 60s
            labels:
                - "traefik.frontend.rule=Host:demo-dev.cilogon.org"
                - "traefik.backend=cilogon_service-oa4mp-demo"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=cilogon_service_demo_dev_cilogon_org"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=8888"
                - "traefik.frontend.headers.SSLRedirect=true"
                - "traefik.frontend.entryPoints=http,https"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    oa4mp-server:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/oa4mp-server:2
        hostname: dev.cilogon.org
        command: ["catalina.sh", "run"]
        volumes:
            - type: volume
              source: cilogon_service_volume
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - webgateway
            - cilogon_service
        extra_hosts:
            myproxy.cilogon.org: 141.142.149.29
            myproxy2.cilogon.org: 141.142.149.30
            myproxy3.cilogon.org: 141.142.149.31
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 60s
            resources:
                limits:
                    cpus: '0.5'
                    memory: 2048M
                reservations:
                    cpus: '0.25'
                    memory: 512M
            labels:
                - "traefik.frontend.rule=Host:dev.cilogon.org;PathPrefix:/oauth2/{url:(token|userinfo|getcert|register|certs|clients|static|oidc-cm|admin-register|revoke|introspect|device_authorization|device|.well-known)((/[^/]*)*)}"
                - "traefik.frontend.priority=100"
                - "traefik.backend=cilogon_service-oa4mp-server"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=cilogon_service_dev_cilogon_org_oauth2"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=8888"
                - "traefik.frontend.headers.SSLRedirect=true"
                - "traefik.frontend.entryPoints=http,https"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    oa4mp-oauth1:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/oa4mp-oauth1:2
        hostname: dev.cilogon.org
        command: ["catalina.sh", "run"]
        volumes:
            - type: volume
              source: cilogon_service_volume
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - webgateway
            - cilogon_service
        extra_hosts:
            myproxy.cilogon.org: 141.142.149.29
            myproxy2.cilogon.org: 141.142.149.30
            myproxy3.cilogon.org: 141.142.149.31
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 60s
            resources:
                limits:
                    cpus: '0.5'
                    memory: 2048M
                reservations:
                    cpus: '0.25'
                    memory: 512M
            labels:
                - "traefik.frontend.rule=Host:dev.cilogon.org;PathPrefix:/oauth/{url:(initiate|token|getcert|assets)((/[^/]*)*)}"
                - "traefik.frontend.priority=90"
                - "traefik.backend=cilogon_service-oa4mp-oauth1"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=cilogon_service_dev_cilogon_org_oauth1"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=8888"
                - "traefik.frontend.headers.SSLRedirect=true"
                - "traefik.frontend.entryPoints=http,https"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    cilogon-web:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/cilogon-web:15
        hostname: dev.cilogon.org
        command: ["/usr/local/bin/startup.sh"]
        volumes:
            - type: volume
              source: cilogon_service_volume
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - webgateway
            - cilogon_service
        extra_hosts:
            myproxy.cilogon.org: 141.142.149.29
            myproxy2.cilogon.org: 141.142.149.30
            myproxy3.cilogon.org: 141.142.149.31
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 60s
            resources:
                limits:
                    cpus: '0.5'
                    memory: 2048M
                reservations:
                    cpus: '0.25'
                    memory: 512M
            labels:
                - "traefik.frontend.rule=Host:dev.cilogon.org,dev.cilogon.com,dev.cilogon.net,dev.cilogin.org,ecp-dev.cilogon.org"
                - "traefik.frontend.priority=50"
                - "traefik.backend=cilogon_service-cilogon-web"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=cilogon_service_dev_cilogon_org"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=80"
                - "traefik.frontend.headers.SSLRedirect=true"
                - "traefik.frontend.entryPoints=http,https"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    cilogon-cron:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/cilogon-cron:2
        command: ["/usr/sbin/cron", "-f", "-L", "15"]
        volumes:
            - type: volume
              source: cilogon_service_volume
              target: /var/local/cilogon_service
              read_only: false
              volume:
                  nocopy: true
        networks:
            - webgateway
            - cilogon_service
        extra_hosts:
            myproxy.cilogon.org: 141.142.149.29
            myproxy2.cilogon.org: 141.142.149.30
            myproxy3.cilogon.org: 141.142.149.31
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 60s
            labels:
                - "traefik.backend=cilogon_service-cilogon-cron"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

