version: '3.8'

networks:
    cilogon-multi-tenant:
        driver: overlay
        driver_opts:
            subnet: 10.0.100.0/24
            encrypted: 1
    webgateway:
        external: true
    ldapgateway:
        external: true

volumes:
    ldap-state-01:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/var/lib/ldap_01"

    ldap-state-02:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/var/lib/ldap_02"

    ldap-config-01:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/etc/slapd.d/ldap_01"

    ldap-config-02:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/etc/slapd.d/ldap_02"

    ldap-ldif-01:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/ldif/ldap_01"

    ldap-ldif-02:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/ldif/ldap_02"

    ldap-schema:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/schema"
    ldap-backups-01:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_BACKUPS_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/ldif/01"

    ldap-backups-02:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_BACKUPS_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/ldif/02"

    ldap-backups-usr-local:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/usr/local/slapcat"

    comanage-registry-local:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/cilogon_multi_tenant/srv/comanage-registry/local"

services:

    cilogon-multi-tenant-ldap-01:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/comanage-registry-slapd:8
        command: ["slapd", "-d", "256", "-h", "ldapi:/// ldap:///", "-u", "openldap", "-g", "openldap"]
        volumes:
            - type: volume
              source: ldap-state-01
              target: /var/lib/ldap
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-config-01
              target: /etc/ldap/slapd.d
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-ldif-01
              target: /ldif
              read_only: true
              volume:
                nocopy: true
            - type: volume
              source: ldap-schema
              target: /schema
              read_only: true
              volume:
                nocopy: true
        environment:
            - OLC_ROOT_PW_FILE=/run/secrets/cilogon_multi_tenant_olc_root_pw
            - OLC_SUFFIX=dc=cilogon,dc=org
            - OLC_ROOT_DN=cn=admin,dc=cilogon,dc=org
            - OLC_ROOT_DN_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_olc_root_dn_password
            - SYNCREPL_USER_PASSWORD_HASH_FILE=/run/secrets/cilogon_multi_tenant_syncrepl_user_password_hash
        secrets:
            - cilogon_multi_tenant_olc_root_pw
            - cilogon_multi_tenant_olc_root_dn_password
            - cilogon_multi_tenant_syncrepl_user_password_hash
        networks:
            - cilogon-multi-tenant
            - ldapgateway
        healthcheck:
            test: ["CMD", "/usr/bin/ldapsearch", "-LLL", "-H", "ldapi:///", "-Y", "EXTERNAL", "-b", "cn=config"]
            interval: 15s
            timeout: 1s
            retries: 3
            start_period: 5s
        deploy:
            replicas: 1
            placement:
              constraints:
                - "node.role==manager"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    cilogon-multi-tenant-ldap-02:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/comanage-registry-slapd:8
        command: ["slapd", "-d", "256", "-h", "ldapi:/// ldap:///", "-u", "openldap", "-g", "openldap"]
        volumes:
            - type: volume
              source: ldap-state-02
              target: /var/lib/ldap
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-config-02
              target: /etc/ldap/slapd.d
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-ldif-02
              target: /ldif
              read_only: true
              volume:
                nocopy: true
            - type: volume
              source: ldap-schema
              target: /schema
              read_only: true
              volume:
                nocopy: true
        environment:
            - OLC_ROOT_PW_FILE=/run/secrets/cilogon_multi_tenant_olc_root_pw
            - OLC_SUFFIX=dc=cilogon,dc=org
            - OLC_ROOT_DN=cn=admin,dc=cilogon,dc=org
            - OLC_ROOT_DN_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_olc_root_dn_password
            - SYNCREPL_USER_PASSWORD_HASH_FILE=/run/secrets/cilogon_multi_tenant_syncrepl_user_password_hash
        secrets:
            - cilogon_multi_tenant_olc_root_pw
            - cilogon_multi_tenant_olc_root_dn_password
            - cilogon_multi_tenant_syncrepl_user_password_hash
        networks:
            - cilogon-multi-tenant
            - ldapgateway
        healthcheck:
            test: ["CMD", "/usr/bin/ldapsearch", "-LLL", "-H", "ldapi:///", "-Y", "EXTERNAL", "-b", "cn=config"]
            interval: 15s
            timeout: 1s
            retries: 3
            start_period: 5s
        deploy:
            replicas: 1
            placement:
              constraints:
                - "node.role==worker"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    cilogon-multi-tenant-ldif-backup-01:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/ldif-backup:1
        volumes:
            - type: volume
              source: ldap-state-01
              target: /var/lib/ldap
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-config-01
              target: /etc/ldap/slapd.d
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-backups-usr-local
              target: /usr/local/slapcat
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-backups-01
              target: /srv/backups/ldif
              read_only: false
              volume:
                nocopy: true
        environment:
            - LDIF_BACKUP_FILE_PREFIX=cilogon_multi_tenant-01
            - LDIF_CRONTAB=/usr/local/slapcat/etc/openldap-crontab
        networks:
            - cilogon-multi-tenant
        healthcheck:
            test: ["CMD", "/usr/bin/crontab", "-u", "openldap", "-l"]
            interval: 15s
            timeout: 1s
            retries: 3
            start_period: 5s
        deploy:
            replicas: 1
            placement:
              constraints:
                - "node.role==manager"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    cilogon-multi-tenant-ldif-backup-02:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/ldif-backup:1
        volumes:
            - type: volume
              source: ldap-state-02
              target: /var/lib/ldap
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-config-02
              target: /etc/ldap/slapd.d
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-backups-usr-local
              target: /usr/local/slapcat
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: ldap-backups-02
              target: /srv/backups/ldif
              read_only: false
              volume:
                nocopy: true
        environment:
            - LDIF_BACKUP_FILE_PREFIX=cilogon_multi_tenant-02
            - LDIF_CRONTAB=/usr/local/slapcat/etc/openldap-crontab
        networks:
            - cilogon-multi-tenant
        healthcheck:
            test: ["CMD", "/usr/bin/crontab", "-u", "openldap", "-l"]
            interval: 15s
            timeout: 1s
            retries: 3
            start_period: 5s
        deploy:
            replicas: 1
            placement:
              constraints:
                - "node.role==worker"
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    comanage-registry:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/comanage-registry:hotfix-4.0.x-1
        volumes:
            - type: volume
              source: comanage-registry-local
              target: /srv/comanage-registry/local
              read_only: false
              volume:
                nocopy: true
        environment:
            - OIDC_CLIENT_ID_FILE=/run/secrets/cilogon_multi_tenant_oidc_client_id 
            - OIDC_CLIENT_SECRET_FILE=/run/secrets/cilogon_multi_tenant_oidc_client_secret 
            - OIDC_PROVIDER_METADATA_URL_FILE=/run/secrets/cilogon_multi_tenant_oidc_provider_metadata_url 
            - OIDC_CRYPTO_PASSPHRASE_FILE=/run/secrets/cilogon_multi_tenant_oidc_crypto_passphrase 
            - COMANAGE_REGISTRY_ADMIN_GIVEN_NAME=ScottCmpAdmin
            - COMANAGE_REGISTRY_ADMIN_FAMILY_NAME=Koranda
            - COMANAGE_REGISTRY_ADMIN_USERNAME=http://cilogon.org/serverT/users/64703
            - COMANAGE_REGISTRY_DATASOURCE=Database/Mysql
            - COMANAGE_REGISTRY_DATABASE=registry_dev
            - COMANAGE_REGISTRY_DATABASE_HOST_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_database_host
            - COMANAGE_REGISTRY_DATABASE_USER=registry_userdev
            - COMANAGE_REGISTRY_DATABASE_USER_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_database_user_password
            - COMANAGE_REGISTRY_EMAIL_TRANSPORT=Smtp
            - COMANAGE_REGISTRY_EMAIL_HOST=tls://smtp.gmail.com
            - COMANAGE_REGISTRY_EMAIL_PORT=465
            - COMANAGE_REGISTRY_EMAIL_ACCOUNT=registry@cilogon.org
            - COMANAGE_REGISTRY_EMAIL_ACCOUNT_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_email_account_password
            - COMANAGE_REGISTRY_EMAIL_FROM=registry@cilogon.org
            - COMANAGE_REGISTRY_ENABLE_PLUGIN=MediaWikiProvisioner,GithubProvisioner
            - COMANAGE_REGISTRY_SECURITY_SALT_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_security_salt
            - COMANAGE_REGISTRY_SECURITY_SEED_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_security_seed
            - COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN_FILE=/run/secrets/cilogon_multi_tenant_registry_host 
        secrets:
            - cilogon_multi_tenant_comanage_registry_database_user_password
            - cilogon_multi_tenant_comanage_registry_database_host
            - cilogon_multi_tenant_comanage_registry_email_account_password
            - cilogon_multi_tenant_comanage_registry_security_salt
            - cilogon_multi_tenant_comanage_registry_security_seed
            - cilogon_multi_tenant_oidc_client_id
            - cilogon_multi_tenant_oidc_client_secret
            - cilogon_multi_tenant_oidc_provider_metadata_url
            - cilogon_multi_tenant_oidc_crypto_passphrase
            - cilogon_multi_tenant_registry_host
        networks:
            - cilogon-multi-tenant
            - webgateway
        healthcheck:
            test: ["CMD", "curl", "-f", "-I", "http://127.0.0.1/registry/index.php"]
            interval: 15s
            timeout: 1s
            retries: 3
            start_period: 180s
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=webgateway"
                - "traefik.http.routers.cilogon_multi_tenant-comanage-registry-http.entrypoints=web"
                - "traefik.http.routers.cilogon_multi_tenant-comanage-registry-http.rule=Host(`registry-dev.cilogon.org`)"
                - "traefik.http.routers.cilogon_multi_tenant-comanage-registry-http.middlewares=cilogon_multi_tenant-comanage-registry-https"
                - "traefik.http.middlewares.cilogon_multi_tenant-comanage-registry-https.redirectscheme.scheme=https"
                - "traefik.http.routers.cilogon_multi_tenant-comanage-registry.entrypoints=websecure"
                - "traefik.http.routers.cilogon_multi_tenant-comanage-registry.rule=Host(`registry-dev.cilogon.org`)"
                - "traefik.http.routers.cilogon_multi_tenant-comanage-registry.tls=true"
                - "traefik.http.routers.cilogon_multi_tenant-comanage-registry.middlewares=cilogon_multi_tenant-comanage-registry"
                - "traefik.http.services.cilogon_multi_tenant-comanage-registry.loadbalancer.server.port=80"
                - "traefik.http.services.cilogon_multi_tenant-comanage-registry.loadbalancer.sticky.cookie=true"
                - "traefik.http.services.cilogon_multi_tenant-comanage-registry.loadbalancer.sticky.cookie.name=_cilogon_multi_tenant_dev"
                - "traefik.http.services.cilogon_multi_tenant-comanage-registry.loadbalancer.sticky.cookie.secure=true"
                - "traefik.http.services.cilogon_multi_tenant-comanage-registry.loadbalancer.sticky.cookie.httpOnly=true"
                - "traefik.http.middlewares.cilogon_multi_tenant-comanage-registry.headers.stsseconds=63072000"
                - "traefik.http.middlewares.cilogon_multi_tenant-comanage-registry.headers.stsincludesubdomains=true"
                - "traefik.http.services.cilogon_multi_tenant-comanage-registry.loadbalancer.healthcheck.path=/registry/index.php"
                - "traefik.http.services.cilogon_multi_tenant-comanage-registry.loadbalancer.healthcheck.interval=5s"
                - "traefik.http.services.cilogon_multi_tenant-comanage-registry.loadbalancer.healthcheck.timeout=1s"
            replicas: 1
            placement:
                max_replicas_per_node: 1
            update_config:
                parallelism: 1
                delay: 120s
                failure_action: rollback
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    comanage-registry-cron:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/comanage-registry-cron:hotfix-4.0.x-1
        volumes:
            - type: volume
              source: comanage-registry-local
              target: /srv/comanage-registry/local
              read_only: false
              volume:
                nocopy: true
        networks:
            - cilogon-multi-tenant
        healthcheck:
            test: ["CMD", "/usr/bin/crontab", "-l", "-u", "www-data"]
            interval: 15s
            timeout: 1s
            retries: 3
            start_period: 5s
        deploy:
            labels:
                - "traefik.enable=false"
            replicas: 1
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

secrets:
    cilogon_multi_tenant_comanage_registry_database_user_password:
        external: true
    cilogon_multi_tenant_comanage_registry_database_host:
        external: true
    cilogon_multi_tenant_comanage_registry_email_account_password:
        external: true
    cilogon_multi_tenant_comanage_registry_security_salt:
        external: true
    cilogon_multi_tenant_comanage_registry_security_seed:
        external: true
    cilogon_multi_tenant_olc_root_pw:
        external: true
    cilogon_multi_tenant_olc_root_dn_password:
        external: true
    cilogon_multi_tenant_oidc_client_id:
        external: true
    cilogon_multi_tenant_oidc_client_secret:
        external: true
    cilogon_multi_tenant_oidc_provider_metadata_url:
        external: true
    cilogon_multi_tenant_oidc_crypto_passphrase:
        external: true
    cilogon_multi_tenant_registry_host:
        external: true
    cilogon_multi_tenant_syncrepl_user_password_hash:
        external: true
