version: '3.1'

networks:
    cilogon-multi-tenant:
        driver: overlay
        driver_opts:
            subnet: 10.0.100.0/24
            encrypted: 1
    webgateway:
        external: true
    ldapgateway:
        external: true

services:

    cilogon-multi-tenant-ldap-01:
        image: sphericalcowgroup/comanage-registry-slapd:2
        command: ["slapd", "-d", "256", "-h", "ldapi:/// ldap:///", "-u", "openldap", "-g", "openldap"]
        volumes:
            - /srv/docker/cilogon_multi_tenant/var/lib/ldap_01:/var/lib/ldap
            - /srv/docker/cilogon_multi_tenant/etc/slapd.d/ldap_01:/etc/ldap/slapd.d
            - /srv/docker/cilogon_multi_tenant/schema/cilogonperson.ldif:/schema/cilogonperson.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/first/admin-first-all-create_syncrepl_user.ldif:/ldif/admin/first/create_syncrepl_user.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/config/config-always-all-olcAccess.ldif:/ldif/config/olcAccess.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/config/config-always-all-olcAttributeOptions.ldif:/ldif/config/config-always-all-olcAttributeOptions.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/config/first/config-first-all-olcLimits.ldif:/ldif/config/first/olcLimits.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/config/first/config-first-01-olcServerID.ldif:/ldif/config/first/olcServerID.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_01.ldif:/ldif/admin/admin-always-01-CO_01.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_AUS.ldif:/ldif/admin/admin-always-01-CO_AUS.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_CCAST.ldif:/ldif/admin/admin-always-01-CO_CCAST.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_CILogon.ldif:/ldif/admin/admin-always-01-CO_CILogon.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_CloudBank.ldif:/ldif/admin/admin-always-01-CO_CloudBank.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_FABRIC.ldif:/ldif/admin/admin-always-01-CO_FABRIC.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_GalaxyTest.ldif:/ldif/admin/admin-always-01-CO_GalaxyTest.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_IceCube.ldif:/ldif/admin/admin-always-01-CO_IceCube.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_ImPACT.ldif:/ldif/admin/admin-always-01-CO_ImPACT.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_MESS.ldif:/ldif/admin/admin-always-01-CO_MESS.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_MGHPCC.ldif:/ldif/admin/admin-always-01-CO_MGHPCC.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_NANOGrav.ldif:/ldif/admin/admin-always-01-CO_NANOGrav.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_OpenIRIS.ldif:/ldif/admin/admin-always-01-CO_OpenIRIS.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_OSG.ldif:/ldif/admin/admin-always-01-CO_OSG.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_SciDAS.ldif:/ldif/admin/admin-always-01-CO_SciDAS.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_Template.ldif:/ldif/admin/admin-always-01-CO_Template.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_01/admin/admin-always-01-CO_XSEDE.ldif:/ldif/admin/admin-always-01-CO_XSEDE.ldif
        environment:
            - OLC_ROOT_PW_FILE=/run/secrets/cilogon_multi_tenant_olc_root_pw
            - OLC_SUFFIX=dc=cilogon,dc=org
            - OLC_ROOT_DN=cn=admin,dc=cilogon,dc=org
            - OLC_ROOT_DN_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_olc_root_dn_password
            - SYNCREPL_USER_PASSWORD_HASH_FILE=/run/secrets/cilogon_multi_tenant_syncrepl_user_password_hash
        secrets:
            - cilogon_multi_tenant_olc_root_pw
            - cilogon_multi_tenant_olc_root_dn_password
            - cilogon_multi_tenant_syncrepl_user_password_hash
        networks:
            - cilogon-multi-tenant
            - ldapgateway
        deploy:
            replicas: 1
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    cilogon-multi-tenant-ldap-02:
        image: sphericalcowgroup/comanage-registry-slapd:2
        command: ["slapd", "-d", "256", "-h", "ldapi:/// ldap:///", "-u", "openldap", "-g", "openldap"]
        volumes:
            - /srv/docker/cilogon_multi_tenant/var/lib/ldap_02:/var/lib/ldap
            - /srv/docker/cilogon_multi_tenant/etc/slapd.d/ldap_02:/etc/ldap/slapd.d
            - /srv/docker/cilogon_multi_tenant/schema/cilogonperson.ldif:/schema/cilogonperson.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_02/admin/first/admin-first-all-create_syncrepl_user.ldif:/ldif/admin/first/create_syncrepl_user.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_02/config/config-always-all-olcAccess.ldif:/ldif/config/olcAccess.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_02/config/config-always-all-olcAttributeOptions.ldif:/ldif/config/config-always-all-olcAttributeOptions.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_02/config/first/config-first-all-olcLimits.ldif:/ldif/config/first/olcLimits.ldif
            - /srv/docker/cilogon_multi_tenant/ldif/ldap_02/config/first/config-first-02-olcServerID.ldif:/ldif/config/first/olcServerID.ldif
        environment:
            - OLC_ROOT_PW_FILE=/run/secrets/cilogon_multi_tenant_olc_root_pw
            - OLC_SUFFIX=dc=cilogon,dc=org
            - OLC_ROOT_DN=cn=admin,dc=cilogon,dc=org
            - OLC_ROOT_DN_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_olc_root_dn_password
            - SYNCREPL_USER_PASSWORD_HASH_FILE=/run/secrets/cilogon_multi_tenant_syncrepl_user_password_hash
        secrets:
            - cilogon_multi_tenant_olc_root_pw
            - cilogon_multi_tenant_olc_root_dn_password
            - cilogon_multi_tenant_syncrepl_user_password_hash
        networks:
            - cilogon-multi-tenant
            - ldapgateway
        deploy:
            replicas: 1
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    comanage-registry:
        image: cilogon/comanage-registry:3.2.5-2
        volumes:
            - /srv/docker/cilogon_multi_tenant/srv/comanage-registry/local:/srv/comanage-registry/local
        environment:
            - OIDC_CLIENT_ID_FILE=/run/secrets/cilogon_multi_tenant_oidc_client_id 
            - OIDC_CLIENT_SECRET_FILE=/run/secrets/cilogon_multi_tenant_oidc_client_secret 
            - OIDC_PROVIDER_METADATA_URL_FILE=/run/secrets/cilogon_multi_tenant_oidc_provider_metadata_url 
            - OIDC_CRYPTO_PASSPHRASE_FILE=/run/secrets/cilogon_multi_tenant_oidc_crypto_passphrase 
            - COMANAGE_REGISTRY_ADMIN_GIVEN_NAME=ScottCmpAdmin
            - COMANAGE_REGISTRY_ADMIN_FAMILY_NAME=Koranda
            - COMANAGE_REGISTRY_ADMIN_USERNAME=http://cilogon.org/serverA/users/22981
            - COMANAGE_REGISTRY_DATASOURCE=Database/Mysql
            - COMANAGE_REGISTRY_DATABASE=registry_test
            - COMANAGE_REGISTRY_DATABASE_HOST_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_database_host
            - COMANAGE_REGISTRY_DATABASE_USER=registry_usertst
            - COMANAGE_REGISTRY_DATABASE_USER_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_database_user_password
            - COMANAGE_REGISTRY_EMAIL_TRANSPORT=Smtp
            - COMANAGE_REGISTRY_EMAIL_HOST=tls://smtp.gmail.com
            - COMANAGE_REGISTRY_EMAIL_PORT=465
            - COMANAGE_REGISTRY_EMAIL_ACCOUNT=registry@cilogon.org
            - COMANAGE_REGISTRY_EMAIL_ACCOUNT_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_email_account_password
            - COMANAGE_REGISTRY_EMAIL_FROM=registry@cilogon.org
            - COMANAGE_REGISTRY_ENABLE_PLUGIN=MediaWikiProvisioner
            - COMANAGE_REGISTRY_SECURITY_SALT_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_security_salt
            - COMANAGE_REGISTRY_SECURITY_SEED_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_security_seed
            - COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN_FILE=/run/secrets/cilogon_multi_tenant_registry_host 
        secrets:
            - cilogon_multi_tenant_comanage_registry_database_user_password
            - cilogon_multi_tenant_comanage_registry_database_host
            - cilogon_multi_tenant_comanage_registry_email_account_password
            - cilogon_multi_tenant_comanage_registry_security_salt
            - cilogon_multi_tenant_comanage_registry_security_seed
            - cilogon_multi_tenant_oidc_client_id
            - cilogon_multi_tenant_oidc_client_secret
            - cilogon_multi_tenant_oidc_provider_metadata_url
            - cilogon_multi_tenant_oidc_crypto_passphrase
            - cilogon_multi_tenant_registry_host
        networks:
            - cilogon-multi-tenant
            - webgateway
        deploy:
            labels:
                - "traefik.backend=cilogon-multi-tenant-comanage-registry"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host: registry-test.cilogon.org"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=_cilogon_multi_tenant_test"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=80"
            replicas: 2
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

secrets:
    cilogon_multi_tenant_comanage_registry_database_user_password:
        external: true
    cilogon_multi_tenant_comanage_registry_database_host:
        external: true
    cilogon_multi_tenant_comanage_registry_email_account_password:
        external: true
    cilogon_multi_tenant_comanage_registry_security_salt:
        external: true
    cilogon_multi_tenant_comanage_registry_security_seed:
        external: true
    cilogon_multi_tenant_olc_root_pw:
        external: true
    cilogon_multi_tenant_olc_root_dn_password:
        external: true
    cilogon_multi_tenant_oidc_client_id:
        external: true
    cilogon_multi_tenant_oidc_client_secret:
        external: true
    cilogon_multi_tenant_oidc_provider_metadata_url:
        external: true
    cilogon_multi_tenant_oidc_crypto_passphrase:
        external: true
    cilogon_multi_tenant_registry_host:
        external: true
    cilogon_multi_tenant_syncrepl_user_password_hash:
        external: true
