version: '3.1'

networks:
    cilogon-multi-tenant:
        driver: overlay
        driver_opts:
            subnet: 10.0.100.0/24
            encrypted: 1
    webgateway:
        external: true

services:

#    comanage-registry-ldap-master:
#        image: cilogon/comanage-registry-slapd-cilogon
#        volumes:
#            - /srv/docker/cilogon/var/lib/ldap:/var/lib/ldap
#            - /srv/docker/cilogon/etc/ldap/slapd.d:/etc/ldap/slapd.d
#        environment:
#            - SLAPD_CERT_FILE=/run/secrets/cilogon_multi_tenant_slapd_cert_file
#            - SLAPD_PRIVKEY_FILE=/run/secrets/cilogon_multi_tenant_slapd_privkey_file
#            - SLAPD_CHAIN_FILE=/run/secrets/cilogon_multi_tenant_slapd_chain_file
#            - OLC_ROOT_PW_FILE=/run/secrets/cilogon_multi_tenant_olc_root_pw
#            - OLC_SUFFIX=dc=registry,dc=cilogon,dc=org
#            - OLC_ROOT_DN=cn=admin,dc=registry,dc=cilogon,dc=org
#        secrets:
#            - cilogon_multi_tenant_slapd_cert_file
#            - cilogon_multi_tenant_slapd_privkey_file
#            - cilogon_multi_tenant_slapd_chain_file
#            - cilogon_multi_tenant_olc_root_pw
#        networks:
#            - cilogon-multi-tenant
#        ports:
#            - "636:636"
#            - "389:389"
#        deploy:
#            replicas: 1

    comanage-registry:
        image: cilogon/comanage-registry:develop
        volumes:
            - /srv/docker/cilogon_multi_tenant/srv/comanage-registry/local:/srv/comanage-registry/local
        environment:
            - OIDC_CLIENT_ID_FILE=/run/secrets/cilogon_multi_tenant_oidc_client_id 
            - OIDC_CLIENT_SECRET_FILE=/run/secrets/cilogon_multi_tenant_oidc_client_secret 
            - OIDC_PROVIDER_METADATA_URL_FILE=/run/secrets/cilogon_multi_tenant_oidc_provider_metadata_url 
            - OIDC_CRYPTO_PASSPHRASE_FILE=/run/secrets/cilogon_multi_tenant_oidc_crypto_passphrase 
            - SERVER_NAME_FILE=/run/secrets/cilogon_multi_tenant_registry_host 
            - REGISTRY_HOST_FILE=/run/secrets/cilogon_multi_tenant_registry_host 
            - COMANAGE_REGISTRY_ADMIN_GIVEN_NAME=ScottCmpAdmin
            - COMANAGE_REGISTRY_ADMIN_FAMILY_NAME=Koranda
            - COMANAGE_REGISTRY_ADMIN_USERNAME=http://cilogon.org/serverA/users/22981
            - COMANAGE_REGISTRY_DATASOURCE=Database/Mysql
            - COMANAGE_REGISTRY_DATABASE=registry
            - COMANAGE_REGISTRY_DATABASE_HOST_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_database_host
            - COMANAGE_REGISTRY_DATABASE_USER=registry_user
            - COMANAGE_REGISTRY_DATABASE_USER_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_database_user_password
            - COMANAGE_REGISTRY_EMAIL_TRANSPORT=Smtp
            - COMANAGE_REGISTRY_EMAIL_HOST=tls://smtp.gmail.com
            - COMANAGE_REGISTRY_EMAIL_PORT=465
            - COMANAGE_REGISTRY_EMAIL_ACCOUNT_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_email_account
            - COMANAGE_REGISTRY_EMAIL_ACCOUNT_PASSWORD_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_email_account_password
            - COMANAGE_REGISTRY_EMAIL_FROM_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_email_from
            - COMANAGE_REGISTRY_SECURITY_SALT_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_security_salt
            - COMANAGE_REGISTRY_SECURITY_SEED_FILE=/run/secrets/cilogon_multi_tenant_comanage_registry_security_seed
        secrets:
            - cilogon_multi_tenant_comanage_registry_database_user_password
            - cilogon_multi_tenant_comanage_registry_database_host
            - cilogon_multi_tenant_comanage_registry_email_account
            - cilogon_multi_tenant_comanage_registry_email_account_password
            - cilogon_multi_tenant_comanage_registry_email_from
            - cilogon_multi_tenant_comanage_registry_security_salt
            - cilogon_multi_tenant_comanage_registry_security_seed
            - cilogon_multi_tenant_oidc_client_id
            - cilogon_multi_tenant_oidc_client_secret
            - cilogon_multi_tenant_oidc_provider_metadata_url
            - cilogon_multi_tenant_oidc_crypto_passphrase
            - cilogon_multi_tenant_registry_host
        networks:
            - cilogon-multi-tenant
            - webgateway
        deploy:
            labels:
                - "traefik.backend=comanage-registry"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host: registry-dev.cilogon.org"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=_cilogon_multi_tenant"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=80"
            replicas: 1

secrets:
    cilogon_multi_tenant_comanage_registry_database_user_password:
        external: true
    cilogon_multi_tenant_comanage_registry_database_host:
        external: true
    cilogon_multi_tenant_comanage_registry_email_account:
        external: true
    cilogon_multi_tenant_comanage_registry_email_account_password:
        external: true
    cilogon_multi_tenant_comanage_registry_email_from:
        external: true
    cilogon_multi_tenant_comanage_registry_security_salt:
        external: true
    cilogon_multi_tenant_comanage_registry_security_seed:
        external: true
    cilogon_multi_tenant_slapd_cert_file:
        external: true
    cilogon_multi_tenant_slapd_privkey_file:
        external: true
    cilogon_multi_tenant_slapd_chain_file:
        external: true
    cilogon_multi_tenant_olc_root_pw:
        external: true
    cilogon_multi_tenant_oidc_client_id:
        external: true
    cilogon_multi_tenant_oidc_client_secret:
        external: true
    cilogon_multi_tenant_oidc_provider_metadata_url:
        external: true
    cilogon_multi_tenant_oidc_crypto_passphrase:
        external: true
    cilogon_multi_tenant_registry_host:
        external: true
