version: '3.1'

networks:
    cilogon-multi-tenant:
        driver: overlay
        driver_opts:
            subnet: 10.0.100.0/24
            encrypted: 1
    proxy:
        external: true

services:

    comanage-registry-database:
        image: mariadb
        volumes:
            - /srv/docker/cilogon/var/lib/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password 
            - MYSQL_DATABASE=registry
            - MYSQL_USER=registry_user
            - MYSQL_PASSWORD_FILE=/run/secrets/mysql_registry_user_password
        secrets:
            - mysql_root_password
            - mysql_registry_user_password
        networks:
            - cilogon-multi-tenant
        deploy:
            replicas: 1

    comanage-registry-ldap:
        image: cilogon/comanage-registry-slapd-cilogon
        volumes:
            - /srv/docker/cilogon/var/lib/ldap:/var/lib/ldap
            - /srv/docker/cilogon/etc/ldap/slapd.d:/etc/ldap/slapd.d
        environment:
            - SLAPD_CERT_FILE=/run/secrets/slapd_cert_file
            - SLAPD_PRIVKEY_FILE=/run/secrets/slapd_privkey_file
            - SLAPD_CHAIN_FILE=/run/secrets/slapd_chain_file
            - OLC_ROOT_PW_FILE=/run/secrets/olc_root_pw
            - OLC_SUFFIX=dc=cilogon,dc=org
            - OLC_ROOT_DN=cn=admin,dc=cilogon,dc=org
        secrets:
            - slapd_cert_file
            - slapd_privkey_file
            - slapd_chain_file
            - olc_root_pw
        networks:
            - cilogon-multi-tenant
        ports:
            - "636:636"
            - "389:389"
        deploy:
            replicas: 1

    comanage-registry:
        image: cilogon/comanage-registry:hotfix-2.0.x
        volumes:
            - /srv/docker/cilogon/srv/comanage-registry/local:/srv/comanage-registry/local
        environment:
            - OIDC_CLIENT_ID_FILE=/run/secrets/oidc_client_id 
            - OIDC_CLIENT_SECRET_FILE=/run/secrets/oidc_client_secret 
            - OIDC_PROVIDER_METADATA_URL_FILE=/run/secrets/oidc_provider_metadata_url 
            - OIDC_CRYPTO_PASSPHRASE_FILE=/run/secrets/oidc_crypto_passphrase 
            - REGISTRY_HOST_FILE=/run/secrets/registry_host 
            - HTTPS_CERT_FILE=/run/secrets/https_cert_file 
            - HTTPS_PRIVKEY_FILE=/run/secrets/https_privkey_file 
            - COMANAGE_REGISTRY_ADMIN_GIVEN_NAME=ScottCmpAdmin
            - COMANAGE_REGISTRY_ADMIN_FAMILY_NAME=Koranda
            - COMANAGE_REGISTRY_ADMIN_USERNAME=http://cilogon.org/serverA/users/22981
            - COMANAGE_REGISTRY_DATASOURCE=Database/Mysql
            - COMANAGE_REGISTRY_DATABASE=registry
            - COMANAGE_REGISTRY_DATABASE_HOST=comanage-registry-database
            - COMANAGE_REGISTRY_DATABASE_USER=registry_user
            - COMANAGE_REGISTRY_DATABASE_USER_PASSWORD_FILE=/run/secrets/comanage_registry_database_user_password
            - COMANAGE_REGISTRY_EMAIL_TRANSPORT=Smtp
            - COMANAGE_REGISTRY_EMAIL_HOST=smtp.ncsa.uiuc.edu
            - COMANAGE_REGISTRY_EMAIL_PORT=25
            - COMANAGE_REGISTRY_SECURITY_SALT_FILE=/run/secrets/comanage_registry_security_salt
            - COMANAGE_REGISTRY_SECURITY_SEED_FILE=/run/secrets/comanage_registry_security_seed
        secrets:
            - comanage_registry_database_user_password
            - comanage_registry_security_salt
            - comanage_registry_security_seed
            - oidc_client_id
            - oidc_client_secret
            - oidc_provider_metadata_url
            - oidc_crypto_passphrase
            - registry_host
            - https_cert_file
            - https_privkey_file
        networks:
            - cilogon-multi-tenant
            - proxy
        deploy:
            replicas: 1
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                - com.df.port=80
                - com.df.servicePath=/
                - com.df.serviceDomain=registry-dev.cilogon.org
                - com.df.addReqHeader=X-Forwarded-Port %[dst_port]
                - com.df.xForwardedProto=true

secrets:
    comanage_registry_database_user_password:
        external: true
    comanage_registry_security_salt:
        external: true
    comanage_registry_security_seed:
        external: true
    mysql_root_password:
        external: true
    mysql_registry_user_password:
        external: true  
    slapd_cert_file:
        external: true
    slapd_privkey_file:
        external: true
    slapd_chain_file:
        external: true
    olc_root_pw:
        external: true
    oidc_client_id:
        external: true
    oidc_client_secret:
        external: true
    oidc_provider_metadata_url:
        external: true
    oidc_crypto_passphrase:
        external: true
    registry_host:
        external: true
    https_cert_file:
        external: true
    https_privkey_file:
        external: true
