version: '3.1'

networks:
    gw-astronomy:
        driver: overlay
        driver_opts:
            subnet: 10.0.101.0/24
            encrypted: 1
    webgateway:
        external: true
    ldapgateway:
        external: true

services:
    aa:
        image: cilogon/comanage-registry-saml-aa
        volumes:
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/conf/attribute-filter.xml:/opt/shibboleth-idp/conf/attribute-filter.xml
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/conf/attribute-resolver.xml:/opt/shibboleth-idp/conf/attribute-resolver.xml
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/conf/metadata-providers.xml:/opt/shibboleth-idp/conf/metadata-providers.xml
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/credentials/inc-md-cert.pem:/opt/shibboleth-idp/credentials/inc-md-cert.pem
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/credentials/login.ligo.org.cert.LIGOCA.pem:/opt/shibboleth-idp/credentials/login.ligo.org.cert.LIGOCA.pem
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/credentials/mdq-beta-cert.pem:/opt/shibboleth-idp/credentials/mdq-beta-cert.pem
        environment:
            - SAML_AA_ENTITY_ID=https://aa-dev.gw-astronomy.org/aa/shibboleth
            - SAML_AA_SCOPE=gw-astronomy.org
            - SAML_AA_SIGNING_CERT_FILE=/var/run/secrets/gw_astronomy_saml_aa_signing_cert
            - SAML_AA_SIGNING_PRIVKEY_FILE=/var/run/secrets/gw_astronomy_saml_aa_privkey
        secrets:
            - gw_astronomy_saml_aa_signing_cert
            - gw_astronomy_saml_aa_privkey
        networks:
            - gw-astronomy
            - webgateway
        deploy:
            labels:
                - "traefik.backend=gw-astronomy-aa"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host: aa-dev.gw-astronomy.org"
                - "traefik.frontend.passTLSCert=true"
                - "traefik.port=8080"
            replicas: 1

    gw-astronomy-ldap-master:
        image: cilogon/comanage-registry-slapd-cilogon
        volumes:
            - /srv/docker/gw-astronomy/var/lib/ldap:/var/lib/ldap
            - /srv/docker/gw-astronomy/etc/ldap/slapd.d:/etc/ldap/slapd.d
        environment:
            - OLC_ROOT_PW_FILE=/run/secrets/gw_astronomy_olc_root_pw
            - OLC_SUFFIX=dc=gwastronomy-data,dc=cgca,dc=uwm,dc=edu
            - OLC_ROOT_DN=cn=admin,dc=gwastronomy-data,dc=cgca,dc=uwm,dc=edu
        secrets:
            - gw_astronomy_olc_root_pw
        networks:
            - gw-astronomy
            - ldapgateway
        deploy:
            replicas: 1

secrets:
    gw_astronomy_saml_aa_signing_cert:
        external: true
    gw_astronomy_saml_aa_privkey:
        external: true
    gw_astronomy_olc_root_pw:
        external: true

