version: '3.1'

networks:
    gw-astronomy:
        driver: overlay
        driver_opts:
            subnet: 10.0.101.0/24
            encrypted: 1
    webgateway:
        external: true
    ldapgateway:
        external: true

services:
    aa:
        image: cilogon/comanage-registry-saml-aa:4.0.0
        volumes:
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/conf/attribute-filter.xml:/opt/shibboleth-idp/conf/attribute-filter.xml
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/conf/attribute-resolver.xml:/opt/shibboleth-idp/conf/attribute-resolver.xml
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/conf/metadata-providers.xml:/opt/shibboleth-idp/conf/metadata-providers.xml
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/credentials/inc-md-cert.pem:/opt/shibboleth-idp/credentials/inc-md-cert.pem
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/credentials/login.ligo.org.cert.LIGOCA.pem:/opt/shibboleth-idp/credentials/login.ligo.org.cert.LIGOCA.pem
            - /srv/docker/gw-astronomy/opt/shibboleth-idp/credentials/mdq-beta-cert.pem:/opt/shibboleth-idp/credentials/mdq-beta-cert.pem
        environment:
            - SAML_AA_ENTITY_ID=https://aa.gw-astronomy.org/aa/shibboleth
            - SAML_AA_SCOPE=gw-astronomy.org
            - SAML_AA_SIGNING_CERT_FILE=/var/run/secrets/gw_astronomy_saml_aa_signing_cert
            - SAML_AA_SIGNING_PRIVKEY_FILE=/var/run/secrets/gw_astronomy_saml_aa_privkey
        secrets:
            - gw_astronomy_saml_aa_signing_cert
            - gw_astronomy_saml_aa_privkey
        networks:
            - gw-astronomy
            - webgateway
        deploy:
            labels:
                - "traefik.backend=gw-astronomy-aa"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host: aa.gw-astronomy.org"
                - "traefik.port=8080"
            replicas: 3
            update_config:
                parallelism: 1
                delay: 60s
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    gw-astronomy-ldap-01:
        image: sphericalcowgroup/comanage-registry-slapd
        command: ["slapd", "-d", "256", "-h", "ldapi:/// ldap:///", "-u", "openldap", "-g", "openldap"]
        volumes:
            - /srv/docker/gw-astronomy/var/lib/ldap_01:/var/lib/ldap
            - /srv/docker/gw-astronomy/etc/slapd.d/ldap_01:/etc/ldap/slapd.d
            - /srv/docker/gw-astronomy/schema/kerberos.ldif:/schema/kerberos.ldif
            - /srv/docker/gw-astronomy/schema/ligo.ldif:/schema/ligo.ldif
            - /srv/docker/gw-astronomy/schema/cilogonperson.ldif:/schema/cilogonperson.ldif
            - /srv/docker/gw-astronomy/ldif/admin-first-all-create_syncrepl_user.ldif:/ldif/admin/first/create_syncrepl_user.ldif
            - /srv/docker/gw-astronomy/ldif/config-always-all-olcAccess.ldif:/ldif/config/olcAccess.ldif
            - /srv/docker/gw-astronomy/ldif/config-first-all-olcLimits.ldif:/ldif/config/first/olcLimits.ldif
            - /srv/docker/gw-astronomy/ldif/config-first-01-olcServerID.ldif:/ldif/config/first/olcServerID.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_01.ldif:/ldif/admin/01.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_CALICO.ldif:/ldif/admin/CALICO.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_GWHEN.ldif:/ldif/admin/GWHEN.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_gwic-3g-sct.ldif:/ldif/admin/gwic-3g-sct.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_gwic-3g-rdcoord.ldif:/ldif/admin/gwic-3g-rdcoord.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_GWIC.ldif:/ldif/admin/GWIC.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_GWNU.ldif:/ldif/admin/GWNU.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_HTCondor.ldif:/ldif/admin/HTCondor.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_KAGRA-LIGO.ldif:/ldif/admin/KAGRA-LIGO.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_LSC-OSG.ldif:/ldif/admin/LSC-OSG.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_LV-EM.ldif:/ldif/admin/LV-EM.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_openLVEM.ldif:/ldif/admin/openLVEM.ldif
            - /srv/docker/gw-astronomy/ldif/admin-always-01-CO_OZGRAV.ldif:/ldif/admin/OZGRAV.ldif

        environment:
            - OLC_ROOT_PW_FILE=/run/secrets/gw_astronomy_olc_root_pw
            - OLC_SUFFIX=dc=gwastronomy-data,dc=cgca,dc=uwm,dc=edu
            - OLC_ROOT_DN=cn=admin,dc=gwastronomy-data,dc=cgca,dc=uwm,dc=edu
            - OLC_ROOT_DN_PASSWORD_FILE=/run/secrets/gw_astronomy_olc_root_dn_password
            - SYNCREPL_USER_PASSWORD_HASH_FILE=/run/secrets/gw_astronomy_syncrepl_user_password_hash
        secrets:
            - gw_astronomy_olc_root_pw
            - gw_astronomy_olc_root_dn_password
            - gw_astronomy_syncrepl_user_password_hash
        networks:
            - gw-astronomy
            - ldapgateway
        deploy:
            replicas: 1
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    gw-astronomy-ldap-02:
        image: sphericalcowgroup/comanage-registry-slapd
        command: ["slapd", "-d", "256", "-h", "ldapi:/// ldap:///", "-u", "openldap", "-g", "openldap"]
        volumes:
            - /srv/docker/gw-astronomy/var/lib/ldap_02:/var/lib/ldap
            - /srv/docker/gw-astronomy/etc/slapd.d/ldap_02:/etc/ldap/slapd.d
            - /srv/docker/gw-astronomy/schema/kerberos.ldif:/schema/kerberos.ldif
            - /srv/docker/gw-astronomy/schema/ligo.ldif:/schema/ligo.ldif
            - /srv/docker/gw-astronomy/schema/cilogonperson.ldif:/schema/cilogonperson.ldif
            - /srv/docker/gw-astronomy/ldif/admin-first-all-create_syncrepl_user.ldif:/ldif/admin/first/create_syncrepl_user.ldif
            - /srv/docker/gw-astronomy/ldif/config-always-all-olcAccess.ldif:/ldif/config/olcAccess.ldif
            - /srv/docker/gw-astronomy/ldif/config-first-all-olcLimits.ldif:/ldif/config/first/olcLimits.ldif
            - /srv/docker/gw-astronomy/ldif/config-first-02-olcServerID.ldif:/ldif/config/first/olcServerID.ldif
        environment:
            - OLC_ROOT_PW_FILE=/run/secrets/gw_astronomy_olc_root_pw
            - OLC_SUFFIX=dc=gwastronomy-data,dc=cgca,dc=uwm,dc=edu
            - OLC_ROOT_DN=cn=admin,dc=gwastronomy-data,dc=cgca,dc=uwm,dc=edu
            - OLC_ROOT_DN_PASSWORD_FILE=/run/secrets/gw_astronomy_olc_root_dn_password
            - SYNCREPL_USER_PASSWORD_HASH_FILE=/run/secrets/gw_astronomy_syncrepl_user_password_hash
        secrets:
            - gw_astronomy_olc_root_pw
            - gw_astronomy_olc_root_dn_password
            - gw_astronomy_syncrepl_user_password_hash
        networks:
            - gw-astronomy
            - ldapgateway
        deploy:
            replicas: 1
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    comanage-registry:
        image: cilogon/comanage-registry:3.2.1-1
        volumes:
            - /srv/docker/gw-astronomy/srv/comanage-registry/local:/srv/comanage-registry/local
            - /srv/docker/gw-astronomy/srv/comanage-registry/app/webroot/favicon.ico:/srv/comanage-registry/app/webroot/favicon.ico
        environment:
            - OIDC_CLIENT_ID_FILE=/run/secrets/gw_astronomy_oidc_client_id 
            - OIDC_CLIENT_SECRET_FILE=/run/secrets/gw_astronomy_oidc_client_secret 
            - OIDC_PROVIDER_METADATA_URL_FILE=/run/secrets/gw_astronomy_oidc_provider_metadata_url 
            - OIDC_CRYPTO_PASSPHRASE_FILE=/run/secrets/gw_astronomy_oidc_crypto_passphrase 
            - SERVER_NAME_FILE=/run/secrets/gw_astronomy_registry_host 
            - REGISTRY_HOST_FILE=/run/secrets/gw_astronomy_registry_host 
            - COMANAGE_REGISTRY_ADMIN_GIVEN_NAME=ScottCmpAdmin
            - COMANAGE_REGISTRY_ADMIN_FAMILY_NAME=Koranda
            - COMANAGE_REGISTRY_ADMIN_USERNAME=http://cilogon.org/serverA/users/22981
            - COMANAGE_REGISTRY_DATASOURCE=Database/Mysql
            - COMANAGE_REGISTRY_DATABASE=gw_astronomy_registry
            - COMANAGE_REGISTRY_DATABASE_HOST_FILE=/run/secrets/gw_astronomy_comanage_registry_database_host
            - COMANAGE_REGISTRY_DATABASE_USER=gw_registry
            - COMANAGE_REGISTRY_DATABASE_USER_PASSWORD_FILE=/run/secrets/gw_astronomy_comanage_registry_database_user_password
            - COMANAGE_REGISTRY_EMAIL_TRANSPORT=Smtp
            - COMANAGE_REGISTRY_EMAIL_HOST=tls://smtp.gmail.com
            - COMANAGE_REGISTRY_EMAIL_PORT=465
            - COMANAGE_REGISTRY_EMAIL_ACCOUNT_FILE=/run/secrets/gw_astronomy_comanage_registry_email_account
            - COMANAGE_REGISTRY_EMAIL_ACCOUNT_PASSWORD_FILE=/run/secrets/gw_astronomy_comanage_registry_email_account_password
            - COMANAGE_REGISTRY_EMAIL_FROM_FILE=/run/secrets/gw_astronomy_comanage_registry_email_from
            - COMANAGE_REGISTRY_SECURITY_SALT_FILE=/run/secrets/gw_astronomy_comanage_registry_security_salt
            - COMANAGE_REGISTRY_SECURITY_SEED_FILE=/run/secrets/gw_astronomy_comanage_registry_security_seed
            - GW_ASTRONOMY_GOOGLE_EPPN=1
            - GW_ASTRONOMY_ORCID_EPPN_SCOPE=orcid-saml-gateway.gw-astronomy.org
        secrets:
            - gw_astronomy_comanage_registry_database_user_password
            - gw_astronomy_comanage_registry_database_host
            - gw_astronomy_comanage_registry_email_account
            - gw_astronomy_comanage_registry_email_account_password
            - gw_astronomy_comanage_registry_email_from
            - gw_astronomy_comanage_registry_security_salt
            - gw_astronomy_comanage_registry_security_seed
            - gw_astronomy_oidc_client_id
            - gw_astronomy_oidc_client_secret
            - gw_astronomy_oidc_provider_metadata_url
            - gw_astronomy_oidc_crypto_passphrase
            - gw_astronomy_registry_host
        networks:
            - gw-astronomy
            - webgateway
        deploy:
            labels:
                - "traefik.backend=gw-astronomy-comanage-registry"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host: registry.gw-astronomy.org"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=_gw_astronomy_prod"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=80"
            replicas: 3
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    orcid-saml-gateway:
        image: cilogon/comanage-registry-orcid-saml-gateway:1
        volumes:
            - /srv/docker/gw-astronomy/opt/satosa/orcid-saml-gateway-sp-metadata.xml:/opt/satosa/orcid-saml-gateway-sp-metadata.xml
        environment:
            - OIDC_CLIENT_ID_FILE=/var/run/secrets/gw_astronomy_orcid_saml_gateway_oidc_client_id 
            - OIDC_CLIENT_SECRET_FILE=/var/run/secrets/gw_astronomy_orcid_saml_gateway_oidc_client_secret
            - SATOSA_PROXY_BASE=https://orcid-saml-gateway.gw-astronomy.org
            - SATOSA_SAML_FRONTEND_ATTRIBUTE_SCOPE=orcid-saml-gateway.gw-astronomy.org
            - SATOSA_SAML_FRONTEND_CERT_FILE=/var/run/secrets/gw_astronomy_orcid_saml_gateway_satosa_saml_frontend_cert
            - SATOSA_SAML_FRONTEND_KEY_FILE=/var/run/secrets/gw_astronomy_orcid_saml_gateway_satosa_saml_frontend_privkey
            - SATOSA_SAML_FRONTEND_ENTITYID=https://orcid-saml-gateway.gw-astronomy.org/idp
            - SATOSA_SAML_FRONTEND_METADATA_FILE=/opt/satosa/orcid-saml-gateway-sp-metadata.xml
            - SATOSA_STATE_ENCRYPTION_KEY_FILE=/var/run/secrets/gw_astronomy_orcid_saml_gateway_satosa_state_encryption_key
        secrets:
            - gw_astronomy_orcid_saml_gateway_oidc_client_id 
            - gw_astronomy_orcid_saml_gateway_oidc_client_secret
            - gw_astronomy_orcid_saml_gateway_satosa_saml_frontend_cert
            - gw_astronomy_orcid_saml_gateway_satosa_saml_frontend_privkey
            - gw_astronomy_orcid_saml_gateway_satosa_state_encryption_key
        networks:
            - webgateway
        deploy:
            labels:
                - "traefik.backend=gw-astronomy-orcid-saml-gateway"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host: orcid-saml-gateway.gw-astronomy.org"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=_gw_astronomy_orcid_saml_gateway_prod"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=8000"
            replicas: 3
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

secrets:
    gw_astronomy_saml_aa_signing_cert:
        external: true
    gw_astronomy_saml_aa_privkey:
        external: true
    gw_astronomy_olc_root_pw:
        external: true
    gw_astronomy_comanage_registry_database_user_password:
        external: true
    gw_astronomy_comanage_registry_database_host:
        external: true
    gw_astronomy_comanage_registry_email_account:
        external: true
    gw_astronomy_comanage_registry_email_account_password:
        external: true
    gw_astronomy_comanage_registry_email_from:
        external: true
    gw_astronomy_comanage_registry_security_salt:
        external: true
    gw_astronomy_comanage_registry_security_seed:
        external: true
    gw_astronomy_oidc_client_id:
        external: true
    gw_astronomy_oidc_client_secret:
        external: true
    gw_astronomy_oidc_provider_metadata_url:
        external: true
    gw_astronomy_oidc_crypto_passphrase:
        external: true
    gw_astronomy_olc_root_dn_password:
        external: true
    gw_astronomy_orcid_saml_gateway_oidc_client_id:
        external: true
    gw_astronomy_orcid_saml_gateway_oidc_client_secret:
        external: true
    gw_astronomy_orcid_saml_gateway_satosa_saml_frontend_cert:
        external: true
    gw_astronomy_orcid_saml_gateway_satosa_saml_frontend_privkey:
        external: true
    gw_astronomy_orcid_saml_gateway_satosa_state_encryption_key:
        external: true
    gw_astronomy_registry_host:
        external: true
    gw_astronomy_syncrepl_user_password_hash:
        external: true
