version: '3.1'

networks:
    gw-astronomy:
        driver: overlay
        driver_opts:
            subnet: 10.0.101.0/24
            encrypted: 1
    proxy:
        external: true

services:

    comanage-registry-database:
        image: mariadb
        volumes:
            - /srv/docker/gwastro/var/lib/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/gwastro_mysql_root_password 
            - MYSQL_DATABASE=registry
            - MYSQL_USER=registry_user
            - MYSQL_PASSWORD_FILE=/run/secrets/gwastro_mysql_registry_user_password
        secrets:
            - gwastro_mysql_root_password
            - gwastro_mysql_registry_user_password
        networks:
            - gw-astronomy
        deploy:
            replicas: 1

    comanage-registry-ldap:
        image: cilogon/comanage-registry-slapd-cilogon
        volumes:
            - /srv/docker/gwastro/var/lib/ldap:/var/lib/ldap
            - /srv/docker/gwastro/etc/ldap/slapd.d:/etc/ldap/slapd.d
        environment:
            - SLAPD_CERT_FILE=/run/secrets/gwastro_slapd_cert_file
            - SLAPD_PRIVKEY_FILE=/run/secrets/gwastro_slapd_privkey_file
            - SLAPD_CHAIN_FILE=/run/secrets/gwastro_slapd_chain_file
            - OLC_ROOT_PW_FILE=/run/secrets/gwastro_olc_root_pw
            - OLC_SUFFIX=dc=gw-astronomy,dc=org
            - OLC_ROOT_DN=cn=admin,dc=gw-astronomy,dc=org
        secrets:
            - gwastro_slapd_cert_file
            - gwastro_slapd_privkey_file
            - gwastro_slapd_chain_file
            - gwastro_olc_root_pw
        networks:
            - gw-astronomy
        ports:
            - "637:636"
            - "390:389"
        deploy:
            replicas: 1

    comanage-registry:
        image: cilogon/comanage-registry:feature-3.1
        volumes:
            - /srv/docker/gwastro/srv/comanage-registry/local:/srv/comanage-registry/local
        environment:
            - OIDC_CLIENT_ID_FILE=/run/secrets/gwastro_oidc_client_id 
            - OIDC_CLIENT_SECRET_FILE=/run/secrets/gwastro_oidc_client_secret 
            - OIDC_PROVIDER_METADATA_URL_FILE=/run/secrets/gwastro_oidc_provider_metadata_url 
            - OIDC_CRYPTO_PASSPHRASE_FILE=/run/secrets/gwastro_oidc_crypto_passphrase 
            - REGISTRY_HOST_FILE=/run/secrets/gwastro_registry_host 
            - HTTPS_CERT_FILE=/run/secrets/gwastro_https_cert_file 
            - HTTPS_PRIVKEY_FILE=/run/secrets/gwastro_https_privkey_file 
            - COMANAGE_REGISTRY_ADMIN_GIVEN_NAME=ScottCmpAdmin
            - COMANAGE_REGISTRY_ADMIN_FAMILY_NAME=Koranda
            - COMANAGE_REGISTRY_ADMIN_USERNAME=http://cilogon.org/serverA/users/22981
            - COMANAGE_REGISTRY_DATASOURCE=Database/Mysql
            - COMANAGE_REGISTRY_DATABASE=registry
            - COMANAGE_REGISTRY_DATABASE_HOST=comanage-registry-database
            - COMANAGE_REGISTRY_DATABASE_USER=registry_user
            - COMANAGE_REGISTRY_DATABASE_USER_PASSWORD_FILE=/run/secrets/gwastro_comanage_registry_database_user_password
            - COMANAGE_REGISTRY_EMAIL_TRANSPORT=Smtp
            - COMANAGE_REGISTRY_EMAIL_HOST=smtp.ncsa.uiuc.edu
            - COMANAGE_REGISTRY_EMAIL_PORT=25
            - COMANAGE_REGISTRY_SECURITY_SALT_FILE=/run/secrets/gwastro_comanage_registry_security_salt
            - COMANAGE_REGISTRY_SECURITY_SEED_FILE=/run/secrets/gwastro_comanage_registry_security_seed
        secrets:
            - gwastro_comanage_registry_database_user_password
            - gwastro_comanage_registry_security_salt
            - gwastro_comanage_registry_security_seed
            - gwastro_oidc_client_id
            - gwastro_oidc_client_secret
            - gwastro_oidc_provider_metadata_url
            - gwastro_oidc_crypto_passphrase
            - gwastro_registry_host
            - gwastro_https_cert_file
            - gwastro_https_privkey_file
        networks:
            - gw-astronomy
            - proxy
        deploy:
            replicas: 1
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                - com.df.port=80
                - com.df.servicePath=/
                - com.df.serviceDomain=gw-astronomy-dev.cilogon.org
                - com.df.addReqHeader=X-Forwarded-Port %[dst_port]
                - com.df.xForwardedProto=true

secrets:
    gwastro_comanage_registry_database_user_password:
        external: true
    gwastro_comanage_registry_security_salt:
        external: true
    gwastro_comanage_registry_security_seed:
        external: true
    gwastro_mysql_root_password:
        external: true
    gwastro_mysql_registry_user_password:
        external: true  
    gwastro_slapd_cert_file:
        external: true
    gwastro_slapd_privkey_file:
        external: true
    gwastro_slapd_chain_file:
        external: true
    gwastro_olc_root_pw:
        external: true
    gwastro_oidc_client_id:
        external: true
    gwastro_oidc_client_secret:
        external: true
    gwastro_oidc_provider_metadata_url:
        external: true
    gwastro_oidc_crypto_passphrase:
        external: true
    gwastro_registry_host:
        external: true
    gwastro_https_cert_file:
        external: true
    gwastro_https_privkey_file:
        external: true
