version: '3.8'

networks:
    ldapgateway:
        external: true

services:
    ldapgateway:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/comanage-registry-slapd-proxy:8
        command: ["slapd", "-d", "0", "-h", "ldapi:/// ldap:/// ldaps:///", "-u", "openldap", "-g", "openldap"]
        volumes:
            - /srv/docker/ldapgateway/schema/cilogonperson.ldif:/schema/cilogonperson.ldif
            - /srv/docker/ldapgateway/schema/kerberos.ldif:/schema/kerberos.ldif
            - /srv/docker/ldapgateway/schema/ligo.ldif:/schema/ligo.ldif
            - /srv/docker/ldapgateway/ldif/config/ldap_gateway_proxy_config.ldif:/ldif/config/ldap_gateway_proxy_config.ldif
        environment:
            - SLAPD_CERT_FILE=/run/secrets/ldap_gateway_slapd_cert_file_4
            - SLAPD_PRIVKEY_FILE=/run/secrets/ldap_gateway_slapd_privkey_file_4
            - SLAPD_CHAIN_FILE=/run/secrets/ldap_gateway_slapd_chain_file_4
        secrets:
            - ldap_gateway_slapd_cert_file_4
            - ldap_gateway_slapd_privkey_file_4
            - ldap_gateway_slapd_chain_file_4
        networks:
            - ldapgateway
        ports:
            - target: 389
              published: 389
              protocol: tcp
              mode: host
            - target: 636
              published: 636
              protocol: tcp
              mode: host
        deploy:
            mode: global
            placement:
              constraints:
                - node.role == manager
            restart_policy:
              condition: on-failure
            update_config:
              parallelism: 1
              delay: 60s

secrets:
    ldap_gateway_slapd_cert_file_4:
        external: true
    ldap_gateway_slapd_privkey_file_4:
        external: true
    ldap_gateway_slapd_chain_file_4:
        external: true
