version: "3.1"

networks:
    proxy:
        external: true

services:
    proxy:
        image: cilogon/docker-flow-proxy
        ports:
            - 80:80
            - 443:443
        networks:
            - proxy
        environment:
            - LISTENER_ADDRESS=swarm-listener
            - MODE=swarm
            - EXTRA_FRONTEND=redirect scheme https code 301 if !{ ssl_fc }
            - DEBUG=false
        secrets:
            - cert-registry-dev.cilogon.org.pem
            - cert-gw-astronomy-dev.cilogon.org.pem
        deploy:
            replicas: 1

    swarm-listener:
        image: cilogon/docker-flow-swarm-listener
        networks:
            - proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
            - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
        deploy:
            placement:
                constraints: [node.role == manager]

secrets:
    cert-registry-dev.cilogon.org.pem:
        external: true
    cert-gw-astronomy-dev.cilogon.org.pem:
        external: true
