[[tls]]
entryPoints = ["https"]
[tls.certificate]
certFile = "/etc/letsencrypt/live/mdq.scimma.org/fullchain.pem"
keyFile = "/etc/letsencrypt/live/mdq.scimma.org/privkey.pem"

[[tls]]
entryPoints = ["https"]
[tls.certificate]
certFile = "/etc/letsencrypt/live/federation-proxy.scimma.org/fullchain.pem"
keyFile = "/etc/letsencrypt/live/federation-proxy.scimma.org/privkey.pem"

[[tls]]
entryPoints = ["https"]
[tls.certificate]
certFile = "/etc/letsencrypt/live/registry.scimma.org/fullchain.pem"
keyFile = "/etc/letsencrypt/live/registry.scimma.org/privkey.pem"
