[[tls]]
entryPoints = ["https"]
[tls.certificate]
certFile = "/etc/letsencrypt/live/mdq-test.scimma.org/fullchain.pem"
keyFile = "/etc/letsencrypt/live/mdq-test.scimma.org/privkey.pem"

[[tls]]
entryPoints = ["https"]
[tls.certificate]
certFile = "/etc/letsencrypt/live/federation-proxy-test.scimma.org/fullchain.pem"
keyFile = "/etc/letsencrypt/live/federation-proxy-test.scimma.org/privkey.pem"

[[tls]]
entryPoints = ["https"]
[tls.certificate]
certFile = "/etc/letsencrypt/live/registry-test.scimma.org/fullchain.pem"
keyFile = "/etc/letsencrypt/live/registry-test.scimma.org/privkey.pem"
