[[tls]]
entryPoints = ["https"]
[tls.certificate]
certFile = "/etc/letsencrypt/live/mdq-dev.scimma.org/fullchain.pem"
keyFile = "/etc/letsencrypt/live/mdq-dev.scimma.org/privkey.pem"

[[tls]]
entryPoints = ["https"]
[tls.certificate]
certFile = "/etc/letsencrypt/live/federation-proxy-dev.scimma.org/fullchain.pem"
keyFile = "/etc/letsencrypt/live/federation-proxy-dev.scimma.org/privkey.pem"
