debug = false
logLevel = "WARN"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/registry_cilogon_org_https_cert_file"
      keyFile = "/run/secrets/registry_cilogon_org_https_privkey_file"
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/registry_gw_astronomy_org_https_cert_file"
      keyFile = "/run/secrets/registry_gw_astronomy_org_https_privkey_file"
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/gw_astronomy_saml_aa_signing_cert"
      keyFile = "/run/secrets/gw_astronomy_saml_aa_privkey"
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/orcid_saml_gateway_gw_astronomy_org_https_cert_file"
      keyFile = "/run/secrets/orcid_saml_gateway_gw_astronomy_org_https_privkey_file"
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/registry_ligo_org_https_cert_file"
      keyFile = "/run/secrets/registry_ligo_org_https_privkey_file"
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/federation_proxy_ligo_org_https_cert_file"
      keyFile = "/run/secrets/federation_proxy_ligo_org_https_privkey_file"
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/group_registry_ligo_org_https_cert_file"
      keyFile = "/run/secrets/group_registry_ligo_org_https_privkey_file"
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/login_chooser_ligo_org_https_cert_file"
      keyFile = "/run/secrets/login_chooser_ligo_org_https_privkey_file"
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/mdq_ligo_org_https_cert_file"
      keyFile = "/run/secrets/mdq_ligo_org_https_privkey_file"

[accessLog]

[docker]
endpoint = "tcp://dockersocket:2375"
domain = "docker.localhost"
watch = true
swarmmode = true
exposedbydefault = false

[api]
dashboard = true

[ping]

[file]
filename = "/etc/traefik/tls_certificates.toml"
watch = true
