version: "3.7"

networks:
    webgateway:
        external: true
    dockersocket:
        external: true

services:
    dockersocket:
        image: cilogon/cilogon-haproxy:1.9.7
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - SERVICES=1
            - NETWORKS=1
            - TASKS=1
        deploy:
            mode: replicated
            replicas: 3
            placement:
              constraints:
                - node.role == manager
            restart_policy:
              condition: on-failure
            update_config:
              parallelism: 1
              delay: 60s
        networks:
            - dockersocket
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"
          
    webgateway:
        image: traefik:v1.7.20
        volumes:
            - /srv/docker/webgateway/etc/traefik:/etc/traefik
            - /srv/docker/webgateway/etc/letsencrypt:/etc/letsencrypt
        secrets:
            - gw_astronomy_saml_aa_signing_cert
            - gw_astronomy_saml_aa_privkey
            - registry_cilogon_org_https_cert_file
            - registry_cilogon_org_https_privkey_file
            - registry_gw_astronomy_org_https_cert_file
            - registry_gw_astronomy_org_https_privkey_file
            - orcid_saml_gateway_gw_astronomy_org_https_cert_file
            - orcid_saml_gateway_gw_astronomy_org_https_privkey_file
            - registry_ligo_org_https_cert_file
            - registry_ligo_org_https_privkey_file
            - federation_proxy_ligo_org_https_cert_file
            - federation_proxy_ligo_org_https_privkey_file
            - group_registry_ligo_org_https_cert_file
            - group_registry_ligo_org_https_privkey_file
            - login_chooser_ligo_org_https_cert_file
            - login_chooser_ligo_org_https_privkey_file
            - mdq_ligo_org_https_cert_file
            - mdq_ligo_org_https_privkey_file

        networks:
            - webgateway
            - dockersocket
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
        deploy:
            mode: replicated
            replicas: 3
            placement:
              constraints:
                - node.role == manager
            restart_policy:
              condition: on-failure
            update_config:
              parallelism: 1
              delay: 60s
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    getssl:
        image: cilogon/comanage-registry-getssl:1
        volumes:
            - /srv/docker/webgateway/opt/getssl:/opt/getssl
            - /srv/docker/webgateway/etc/letsencrypt:/etc/letsencrypt
        networks:
            - webgateway
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - "traefik.backend=webgateway-getssl"
                - "traefik.docker.network=webgateway"
                - "traefik.enable=true"
                - "traefik.frontend.rule=PathPrefix: /.well-known/acme-challenge"
                - "traefik.frontend.priority=100"
                - "traefik.backend.loadbalancer.stickiness=true"
                - "traefik.backend.loadbalancer.stickiness.cookieName=_webgateway_dev"
                - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security: max-age=63072000; includeSubDomains"
                - "traefik.port=80"
            restart_policy:
              condition: on-failure
            update_config:
              parallelism: 1
              delay: 60s
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

secrets:
    gw_astronomy_saml_aa_signing_cert:
        external: true
    gw_astronomy_saml_aa_privkey:
        external: true
    registry_cilogon_org_https_cert_file:
        external: true
    registry_cilogon_org_https_privkey_file:
        external: true
    registry_gw_astronomy_org_https_cert_file:
        external: true
    registry_gw_astronomy_org_https_privkey_file:
        external: true
    orcid_saml_gateway_gw_astronomy_org_https_cert_file:
        external: true
    orcid_saml_gateway_gw_astronomy_org_https_privkey_file:
        external: true
    registry_ligo_org_https_cert_file:
        external: true
    registry_ligo_org_https_privkey_file:
        external: true
    federation_proxy_ligo_org_https_cert_file:
        external: true
    federation_proxy_ligo_org_https_privkey_file:
        external: true
    group_registry_ligo_org_https_cert_file:
        external: true
    group_registry_ligo_org_https_privkey_file:
        external: true
    login_chooser_ligo_org_https_cert_file:
        external: true
    login_chooser_ligo_org_https_privkey_file:
        external: true
    mdq_ligo_org_https_cert_file:
        external: true
    mdq_ligo_org_https_privkey_file:
        external: true
