version: '3.8'

networks:
    webgateway:
        external: true
    dockersocket:
        external: true

volumes:
    traefik:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/webgateway/etc/traefik"
    letsencrypt:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/webgateway/etc/letsencrypt"
    getssl:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${SRV_DOCKER_NFS_HOST:?err},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
            device: ":/webgateway/opt/getssl"

services:
    dockersocket:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/cilogon-haproxy:1.9.7
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
              read_only: false
        environment:
            - SERVICES=1
            - NETWORKS=1
            - TASKS=1
        deploy:
            mode: replicated
            replicas: 3
            placement:
              constraints:
                - node.role == manager
            restart_policy:
              condition: on-failure
            update_config:
              parallelism: 1
              delay: 60s
        networks:
            - dockersocket
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"
          
    webgateway:
        image: traefik:v2.6.1
        volumes:
            - type: volume
              source: traefik
              target: /etc/traefik
              read_only: true
              volume:
                nocopy: true
            - type: volume
              source: letsencrypt
              target: /etc/letsencrypt
              read_only: true
              volume:
                nocopy: true
        secrets:
            - gw_astronomy_saml_aa_signing_cert
            - gw_astronomy_saml_aa_privkey
            - registry_cilogon_org_https_cert_file
            - registry_cilogon_org_https_privkey_file
            - registry_gw_astronomy_org_https_cert_file
            - registry_gw_astronomy_org_https_privkey_file
            - orcid_saml_gateway_gw_astronomy_org_https_cert_file
            - orcid_saml_gateway_gw_astronomy_org_https_privkey_file
            - registry_ligo_org_https_cert_file
            - registry_ligo_org_https_privkey_file
            - federation_proxy_ligo_org_https_cert_file
            - federation_proxy_ligo_org_https_privkey_file
            - group_registry_ligo_org_https_cert_file
            - group_registry_ligo_org_https_privkey_file
            - login_chooser_ligo_org_https_cert_file
            - login_chooser_ligo_org_https_privkey_file
            - mdq_ligo_org_https_cert_file
            - mdq_ligo_org_https_privkey_file
        networks:
            - webgateway
            - dockersocket
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
        deploy:
            mode: replicated
            replicas: 3
            placement:
              constraints:
                - node.role == manager
            restart_policy:
              condition: on-failure
            update_config:
              parallelism: 1
              delay: 60s
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

    getssl:
        image: 495649616520.dkr.ecr.us-east-2.amazonaws.com/comanage-registry-getssl:1
        volumes:
            - type: volume
              source: getssl
              target: /opt/getssl
              read_only: false
              volume:
                nocopy: true
            - type: volume
              source: letsencrypt
              target: /etc/letsencrypt
              read_only: false
              volume:
                nocopy: true
        networks:
            - webgateway
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=webgateway"
                - "traefik.http.routers.getssl.entrypoints=web"
                - "traefik.http.routers.getssl.rule=PathPrefix(`/.well-known/acme-challenge`)"
                - "traefik.http.routers.getssl.priority=1000"
                - "traefik.http.services.getssl.loadbalancer.server.port=80"
                - "traefik.http.services.getssl.loadbalancer.sticky.cookie=true"
                - "traefik.http.services.getssl.loadbalancer.sticky.cookie.name=_webgateway_prod"
                - "traefik.http.services.getssl.loadbalancer.sticky.cookie.httpOnly=true"
            restart_policy:
              condition: on-failure
            update_config:
              parallelism: 1
              delay: 60s
        logging:
            driver: journald
            options:
                tag: "cilogon_docker_{{.Name}}"

secrets:
    gw_astronomy_saml_aa_signing_cert:
        external: true
    gw_astronomy_saml_aa_privkey:
        external: true
    registry_cilogon_org_https_cert_file:
        external: true
    registry_cilogon_org_https_privkey_file:
        external: true
    registry_gw_astronomy_org_https_cert_file:
        external: true
    registry_gw_astronomy_org_https_privkey_file:
        external: true
    orcid_saml_gateway_gw_astronomy_org_https_cert_file:
        external: true
    orcid_saml_gateway_gw_astronomy_org_https_privkey_file:
        external: true
    registry_ligo_org_https_cert_file:
        external: true
    registry_ligo_org_https_privkey_file:
        external: true
    federation_proxy_ligo_org_https_cert_file:
        external: true
    federation_proxy_ligo_org_https_privkey_file:
        external: true
    group_registry_ligo_org_https_cert_file:
        external: true
    group_registry_ligo_org_https_privkey_file:
        external: true
    login_chooser_ligo_org_https_cert_file:
        external: true
    login_chooser_ligo_org_https_privkey_file:
        external: true
    mdq_ligo_org_https_cert_file:
        external: true
    mdq_ligo_org_https_privkey_file:
        external: true
