version: "3.2"

networks:
    webgateway:
        external: true

services:
    webgateway:
        image: traefik:v1.7.6
        volumes:
            - /srv/docker/webgateway/etc/traefik:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock
        secrets:
            - gw_astronomy_saml_aa_signing_cert
            - gw_astronomy_saml_aa_privkey
            - registry_cilogon_org_https_cert_file
            - registry_cilogon_org_https_privkey_file
            - registry_gw_astronomy_org_https_cert_file
            - registry_gw_astronomy_org_https_privkey_file
        networks:
            - webgateway
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
        deploy:
            mode: global
            placement:
              constraints:
                - node.role == manager
            restart_policy:
              condition: on-failure
            update_config:
              parallelism: 1
              delay: 60s

secrets:
    gw_astronomy_saml_aa_signing_cert:
        external: true
    gw_astronomy_saml_aa_privkey:
        external: true
    registry_cilogon_org_https_cert_file:
        external: true
    registry_cilogon_org_https_privkey_file:
        external: true
    registry_gw_astronomy_org_https_cert_file:
        external: true
    registry_gw_astronomy_org_https_privkey_file:
        external: true
